### ISSUE TITLE
OSX AMD part is not working (v2.3.0)

### ISSUE THREAD

**Issue by djfinch** [fireice-uk/xmr-stak#1218]
Please provide as much as possible information to reproduce the issue.

# Basic information
  - Type of the CPU.
> Intel(R) Xeon(R)  W3530  @ 2.80GHz
  - Type of the GPU (if you try to miner with the GPU).
> ATI HD5770

# Compile issues
  - Which OS do you use?  OSX 10

> ProductName:    Mac OS X
> ProductVersion: 10.11.6
> BuildVersion:   15G19009

<pre>
cmake . -DCUDA_ENABLE=OFF
-- The C compiler identification is AppleClang 8.0.0.8000042
-- The CXX compiler identification is AppleClang 8.0.0.8000042
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for CL_VERSION_2_2
-- Looking for CL_VERSION_2_2 - not found
-- Looking for CL_VERSION_2_1
-- Looking for CL_VERSION_2_1 - not found
-- Looking for CL_VERSION_2_0
-- Looking for CL_VERSION_2_0 - not found
-- Looking for CL_VERSION_1_2
-- Looking for CL_VERSION_1_2 - found
-- Found OpenCL: /System/Library/Frameworks/OpenCL.framework (found version "1.2")
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE
-- Found OpenSSL: /usr/lib/libcrypto.dylib (found version "1.0.2n")
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/user/xmr-stak

make
Scanning dependencies of target xmr-stak-c
[  3%] Building C object CMakeFiles/xmr-stak-c.dir/xmrstak/backend/cpu/crypto/c_blake256.c.o
[  6%] Building C object CMakeFiles/xmr-stak-c.dir/xmrstak/backend/cpu/crypto/c_groestl.c.o
[ 10%] Building C object CMakeFiles/xmr-stak-c.dir/xmrstak/backend/cpu/crypto/c_jh.c.o
[ 13%] Building C object CMakeFiles/xmr-stak-c.dir/xmrstak/backend/cpu/crypto/c_keccak.c.o
[ 16%] Building C object CMakeFiles/xmr-stak-c.dir/xmrstak/backend/cpu/crypto/c_skein.c.o
[ 20%] Linking C static library bin/libxmr-stak-c.a
[ 20%] Built target xmr-stak-c
Scanning dependencies of target xmr-stak-backend
[ 23%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/jconf.cpp.o
[ 26%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/version.cpp.o
[ 30%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/backend/cpu/hwlocMemory.cpp.o

<b>/Users/user/xmr-stak/xmrstak/backend/cpu/hwlocMemory.cpp:40:12: warning: 'hwloc_set_membind_nodeset' is deprecated [-Wdeprecated-declarations]
                        if( 0 > hwloc_set_membind_nodeset(
                                ^
/usr/local/include/hwloc/deprecated.h:100:1: note: 'hwloc_set_membind_nodeset' has been explicitly marked deprecated here
hwloc_set_membind_nodeset(hwloc_topology_t topology, hwloc_const_nodeset_t nodeset, hwloc_membind_policy_t policy, int flags)
^
1 warning generated.</b>

[ 33%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/backend/cpu/jconf.cpp.o
[ 36%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/backend/cpu/minethd.cpp.o
[ 40%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/backend/backendConnector.cpp.o
[ 43%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/backend/globalStates.cpp.o
[ 46%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/backend/cpu/crypto/cryptonight_common.cpp.o
[ 50%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/http/httpd.cpp.o
[ 53%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/http/webdesign.cpp.o
[ 56%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/misc/console.cpp.o
[ 60%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/misc/executor.cpp.o
[ 63%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/misc/telemetry.cpp.o
[ 66%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/misc/uac.cpp.o
[ 70%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/misc/utility.cpp.o
[ 73%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/net/jpsock.cpp.o
[ 76%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/net/socket.cpp.o
[ 80%] Linking CXX static library bin/libxmr-stak-backend.a

<b>/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: bin/libxmr-stak-backend.a(uac.cpp.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: bin/libxmr-stak-backend.a(uac.cpp.o) has no symbols</b>

[ 80%] Built target xmr-stak-backend
Scanning dependencies of target xmr-stak
[ 83%] Building CXX object CMakeFiles/xmr-stak.dir/xmrstak/cli/cli-miner.cpp.o
[ 86%] Linking CXX executable bin/xmr-stak
[ 86%] Built target xmr-stak
Scanning dependencies of target xmrstak_opencl_backend
[ 90%] Building CXX object CMakeFiles/xmrstak_opencl_backend.dir/xmrstak/backend/amd/amd_gpu/gpu.cpp.o

<b>/Users/user/xmr-stak/xmrstak/backend/amd/amd_gpu/gpu.cpp:481:11: warning: using the result of an assignment as a condition without parentheses [-Wparentheses]
                if( ret = clGetProgramInfo(ctx->Program, CL_PROGRAM_BINARIES, num_devices * sizeof(char*), all_programs.data(),NULL) != CL_SUCCESS)
                    ~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/user/xmr-stak/xmrstak/backend/amd/amd_gpu/gpu.cpp:481:11: note: place parentheses around the assignment to silence this warning
                if( ret = clGetProgramInfo(ctx->Program, CL_PROGRAM_BINARIES, num_devices * sizeof(char*), all_programs.data(),NULL) != CL_SUCCESS)
                        ^
                    (                                                                                                                             )
/Users/user/xmr-stak/xmrstak/backend/amd/amd_gpu/gpu.cpp:481:11: note: use '==' to turn this assignment into an equality comparison
                if( ret = clGetProgramInfo(ctx->Program, CL_PROGRAM_BINARIES, num_devices * sizeof(char*), all_programs.data(),NULL) != CL_SUCCESS)
                        ^
                        ==
1 warning generated.</b>

[ 93%] Building CXX object CMakeFiles/xmrstak_opencl_backend.dir/xmrstak/backend/amd/jconf.cpp.o
[ 96%] Building CXX object CMakeFiles/xmrstak_opencl_backend.dir/xmrstak/backend/amd/minethd.cpp.o
[100%] Linking CXX shared library bin/libxmrstak_opencl_backend.dylib
[100%] Built target xmrstak_opencl_backend
</pre>

  ```
cmake -LA .
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/user/xmr-stak
-- Cache values
CMAKE_AR:FILEPATH=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar
CMAKE_BUILD_TYPE:STRING=Release
CMAKE_COLOR_MAKEFILE:BOOL=ON
CMAKE_CXX_COMPILER:FILEPATH=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
CMAKE_CXX_FLAGS:STRING=
CMAKE_CXX_FLAGS_DEBUG:STRING=-g
CMAKE_CXX_FLAGS_MINSIZEREL:STRING=-Os -DNDEBUG
CMAKE_CXX_FLAGS_RELEASE:STRING=-O3 -DNDEBUG
CMAKE_CXX_FLAGS_RELWITHDEBINFO:STRING=-O2 -g -DNDEBUG
CMAKE_C_COMPILER:FILEPATH=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
CMAKE_C_FLAGS:STRING=
CMAKE_C_FLAGS_DEBUG:STRING=-g
CMAKE_C_FLAGS_MINSIZEREL:STRING=-Os -DNDEBUG
CMAKE_C_FLAGS_RELEASE:STRING=-O3 -DNDEBUG
CMAKE_C_FLAGS_RELWITHDEBINFO:STRING=-O2 -g -DNDEBUG
CMAKE_EXE_LINKER_FLAGS:STRING=
CMAKE_EXE_LINKER_FLAGS_DEBUG:STRING=
CMAKE_EXE_LINKER_FLAGS_MINSIZEREL:STRING=
CMAKE_EXE_LINKER_FLAGS_RELEASE:STRING=
CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO:STRING=
CMAKE_EXPORT_COMPILE_COMMANDS:BOOL=OFF
CMAKE_INSTALL_NAME_TOOL:FILEPATH=/usr/bin/install_name_tool
CMAKE_INSTALL_PREFIX:PATH=/Users/user/xmr-stak
CMAKE_LINKER:FILEPATH=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld
CMAKE_LINK_STATIC:BOOL=OFF
CMAKE_MAKE_PROGRAM:FILEPATH=/usr/bin/make
CMAKE_MODULE_LINKER_FLAGS:STRING=
CMAKE_MODULE_LINKER_FLAGS_DEBUG:STRING=
CMAKE_MODULE_LINKER_FLAGS_MINSIZEREL:STRING=
CMAKE_MODULE_LINKER_FLAGS_RELEASE:STRING=
CMAKE_MODULE_LINKER_FLAGS_RELWITHDEBINFO:STRING=
CMAKE_NM:FILEPATH=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/nm
CMAKE_OBJCOPY:FILEPATH=CMAKE_OBJCOPY-NOTFOUND
CMAKE_OBJDUMP:FILEPATH=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/objdump
CMAKE_OSX_ARCHITECTURES:STRING=
CMAKE_OSX_DEPLOYMENT_TARGET:STRING=
CMAKE_OSX_SYSROOT:STRING=
CMAKE_RANLIB:FILEPATH=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib
CMAKE_SHARED_LINKER_FLAGS:STRING=
CMAKE_SHARED_LINKER_FLAGS_DEBUG:STRING=
CMAKE_SHARED_LINKER_FLAGS_MINSIZEREL:STRING=
CMAKE_SHARED_LINKER_FLAGS_RELEASE:STRING=
CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO:STRING=
CMAKE_SKIP_INSTALL_RPATH:BOOL=NO
CMAKE_SKIP_RPATH:BOOL=NO
CMAKE_STATIC_LINKER_FLAGS:STRING=
CMAKE_STATIC_LINKER_FLAGS_DEBUG:STRING=
CMAKE_STATIC_LINKER_FLAGS_MINSIZEREL:STRING=
CMAKE_STATIC_LINKER_FLAGS_RELEASE:STRING=
CMAKE_STATIC_LINKER_FLAGS_RELWITHDEBINFO:STRING=
CMAKE_STRIP:FILEPATH=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip
CMAKE_VERBOSE_MAKEFILE:BOOL=FALSE
CPU_ENABLE:BOOL=ON
CUDA_ENABLE:BOOL=OFF
HWLOC:FILEPATH=/usr/local/lib/libhwloc.dylib
HWLOC_ENABLE:BOOL=ON
HWLOC_INCLUDE_DIR:PATH=/usr/local/include
MHTD:FILEPATH=/usr/local/lib/libmicrohttpd.dylib
MICROHTTPD_ENABLE:BOOL=ON
MTHD_INCLUDE_DIR:PATH=/usr/local/include
OPENSSL_CRYPTO_LIBRARY:FILEPATH=/usr/lib/libcrypto.dylib
OPENSSL_INCLUDE_DIR:PATH=/usr/local/include
OPENSSL_SSL_LIBRARY:FILEPATH=/usr/lib/libssl.dylib
OpenCL_ENABLE:BOOL=ON
OpenCL_INCLUDE_DIR:PATH=/System/Library/Frameworks/OpenCL.framework
OpenCL_LIBRARY:FILEPATH=/System/Library/Frameworks/OpenCL.framework
OpenSSL_ENABLE:BOOL=ON
PKG_CONFIG_EXECUTABLE:FILEPATH=PKG_CONFIG_EXECUTABLE-NOTFOUND
XMR-STAK_COMPILE:STRING=native
  ```

# Issue with the execution
  - Do you compiled the miner by our own?

> YES

  ```
Version: xmr-stak/2.3.0/a036cd8/master/mac/amd-cpu/aeon-cryptonight-monero/20
  ```

# AMD OpenCl issue

  ```
Number of platforms                               1
  Platform Name                                   Apple
  Platform Vendor                                 Apple
  Platform Version                                OpenCL 1.2 (Dec 19 2017 13:26:56)
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_APPLE_SetMemObjectDestructor cl_APPLE_ContextLoggingFunctions cl_APPLE_clut cl_APPLE_query_kernel_names cl_APPLE_gl_sharing cl_khr_gl_event

  Platform Name                                   Apple
Number of devices                                 2
  Device Name                                     Intel(R) Xeon(R) CPU           W3530  @ 2.80GHz
  Device Vendor                                   Intel
  Device Vendor ID                                0xffffffff
  Device Version                                  OpenCL 1.2
  Driver Version                                  1.1
  Device OpenCL C Version                         OpenCL C 1.2
  Device Type                                     CPU
  Device Available                                Yes
  Device Profile                                  FULL_PROFILE
  Max compute units                               8
  Max clock frequency                             2800MHz
  Device Partition                                (core)
    Max number of sub-devices                     0
    Supported partition types                     None
  Max work item dimensions                        3
  Max work item sizes                             1024x1x1
  Max work group size                             1024
  Compiler Available                              Yes
  Linker Available                                Yes
  Preferred work group size multiple              1
  Preferred / native vector sizes
    char                                                16 / 16
    short                                                8 / 8
    int                                                  4 / 4
    long                                                 2 / 2
    half                                                 0 / 0        (n/a)
    float                                                4 / 4
    double                                               2 / 2        (cl_khr_fp64)
  Half-precision Floating-point support           (n/a)
  Single-precision Floating-point support         (core)
    Denormals                                     Yes
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 Yes
    Round to infinity                             Yes
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software               No
    Correctly-rounded divide and sqrt operations  Yes
  Double-precision Floating-point support         (cl_khr_fp64)
    Denormals                                     Yes
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 Yes
    Round to infinity                             Yes
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software               No
  Address bits                                    64, Little-Endian
  Global memory size                              17179869184 (16GiB)
  Error Correction support                        No
  Max memory allocation                           4294967296 (4GiB)
  Unified memory for Host and Device              Yes
  Minimum alignment for any data type             128 bytes
  Alignment of base address                       1024 bits (128 bytes)
  Global Memory cache type                        Read/Write
  Global Memory cache size                        64
  Global Memory cache line size                   8388608 bytes
  Image support                                   Yes
    Max number of samplers per kernel             16
    Max size for 1D images from buffer            65536 pixels
    Max 1D or 2D image array size                 2048 images
    Base address alignment for 2D image buffers   1 bytes
    Pitch alignment for 2D image buffers          1 pixels
    Max 2D image size                             8192x8192 pixels
    Max 3D image size                             2048x2048x2048 pixels
    Max number of read image args                 128
    Max number of write image args                8
  Local memory type                               Global
  Local memory size                               32768 (32KiB)
  Max constant buffer size                        65536 (64KiB)
  Max number of constant args                     8
  Max size of kernel argument                     4096 (4KiB)
  Queue properties
    Out-of-order execution                        No
    Profiling                                     Yes
  Prefer user sync for interop                    Yes
  Profiling timer resolution                      1ns
  Execution capabilities
    Run OpenCL kernels                            Yes
    Run native kernels                            Yes
  printf() buffer size                            1048576 (1024KiB)
  Built-in kernels
  Device Extensions                               cl_APPLE_SetMemObjectDestructor cl_APPLE_ContextLoggingFunctions cl_APPLE_clut cl_APPLE_query_kernel_names cl_APPLE_gl_sharing cl_khr_gl_event cl_khr_fp64 cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_byte_addressable_store cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_3d_image_writes cl_khr_image2d_from_buffer cl_APPLE_fp64_basic_ops cl_APPLE_fixed_alpha_channel_orders cl_APPLE_biased_fixed_point_image_formats cl_APPLE_command_queue_priority

  Device Name                                     ATI Radeon HD 5770
  Device Vendor                                   AMD
  Device Vendor ID                                0x1021b00
  Device Version                                  OpenCL 1.2
  Driver Version                                  1.2 (Jan  9 2018 22:36:38)
  Device OpenCL C Version                         OpenCL C 1.2
  Device Type                                     GPU
  Device Available                                Yes
  Device Profile                                  FULL_PROFILE
  Max compute units                               10
  Max clock frequency                             850MHz
  Device Partition                                (core)
    Max number of sub-devices                     0
    Supported partition types                     None
  Max work item dimensions                        3
  Max work item sizes                             256x256x256
  Max work group size                             256
  Compiler Available                              Yes
  Linker Available                                Yes
  Preferred work group size multiple              64
  Preferred / native vector sizes
    char                                                16 / 16
    short                                                8 / 8
    int                                                  4 / 4
    long                                                 2 / 2
    half                                                 0 / 0        (n/a)
    float                                                4 / 4
    double                                               0 / 0        (n/a)
  Half-precision Floating-point support           (n/a)
  Single-precision Floating-point support         (core)
    Denormals                                     No
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 Yes
    Round to infinity                             Yes
    IEEE754-2008 fused multiply-add               No
    Support is emulated in software               No
    Correctly-rounded divide and sqrt operations  No
  Double-precision Floating-point support         (n/a)
  Address bits                                    32, Little-Endian
  Global memory size                              1073741824 (1024MiB)
  Error Correction support                        No
  Max memory allocation                           268435456 (256MiB)
  Unified memory for Host and Device              No
  Minimum alignment for any data type             128 bytes
  Alignment of base address                       32768 bits (4096 bytes)
  Global Memory cache type                        None
  Image support                                   Yes
    Max number of samplers per kernel             16
    Max size for 1D images from buffer            65536 pixels
    Max 1D or 2D image array size                 2048 images
    Base address alignment for 2D image buffers   256 bytes
    Pitch alignment for 2D image buffers          256 pixels
    Max 2D image size                             16384x16384 pixels
    Max 3D image size                             2048x2048x2048 pixels
    Max number of read image args                 128
    Max number of write image args                8
  Local memory type                               Local
  Local memory size                               32768 (32KiB)
  Max constant buffer size                        65536 (64KiB)
  Max number of constant args                     8
  Max size of kernel argument                     1024
  Queue properties
    Out-of-order execution                        No
    Profiling                                     Yes
  Prefer user sync for interop                    Yes
  Profiling timer resolution                      37ns
  Execution capabilities
    Run OpenCL kernels                            Yes
    Run native kernels                            No
  printf() buffer size                            134217728 (128MiB)
  Built-in kernels
  Device Extensions                               cl_APPLE_SetMemObjectDestructor cl_APPLE_ContextLoggingFunctions cl_APPLE_clut cl_APPLE_query_kernel_names cl_APPLE_gl_sharing cl_khr_gl_event cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_byte_addressable_store cl_khr_image2d_from_buffer cl_khr_depth_images

NULL platform behavior
  clGetPlatformInfo(NULL, CL_PLATFORM_NAME, ...)  Apple
  clGetDeviceIDs(NULL, CL_DEVICE_TYPE_ALL, ...)   Success [P0]
  clCreateContext(NULL, ...) [default]            Success [P0]
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_DEFAULT)  Success (1)
    Platform Name                                 Apple
    Device Name                                   ATI Radeon HD 5770
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CPU)  Success (1)
    Platform Name                                 Apple
    Device Name                                   Intel(R) Xeon(R) CPU           W3530  @ 2.80GHz
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_GPU)  Success (1)
    Platform Name                                 Apple
    Device Name                                   ATI Radeon HD 5770
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ACCELERATOR)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CUSTOM)  <checkNullCtxFromType:2437: create context from type CL_DEVICE_TYPE_CUSTOM : error -30>
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ALL)  Success (2)
    Platform Name                                 Apple
    Device Name                                   ATI Radeon HD 5770
    Device Name                                   Intel(R) Xeon(R) CPU           W3530  @ 2.80GHz
        NOTE:   your OpenCL library only supports OpenCL 1.0,
                but some installed platforms support OpenCL 1.2.
                Programs using 1.2 features may crash
                or behave unexepectedly
  ```

# Stability issue
  - Is the CPU or GPU overclocked?

> NO

  - Is the Main memory of the CPU or GPU undervolted?

> NO
***
I'm not able to compile working OSX version 2.3.0. Previous one works well without any problem but now I'm getting some warnings during compile and then running stak throws these errors and AMD part is not working (but CPU is hashing though).

<pre>
[2018-03-26 21:00:41] : Your CPU doesn't support hardware AES. Don't expect high hashrates.
-------------------------------------------------------------------
xmr-stak 2.3.0 a036cd8

Brought to you by fireice_uk and psychocrypt under GPLv3.
Based on CPU mining code by wolf9466 (heavily optimized by fireice_uk).
Based on OpenCL mining code by wolf9466.

Configurable dev donation level is set to 2.0%

You can use following keys to display reports:
'h' - hashrate
'r' - results
'c' - connection
-------------------------------------------------------------------
[2018-03-26 21:00:43] : Mining coin: cryptonight
[2018-03-26 21:00:43] : Found AMD platform index id = 0, name = Apple
[2018-03-26 21:00:43] : Found OpenCL GPU ATI Radeon HD 5770.
[2018-03-26 21:00:43] : WARNING: Auto detected intensity unexpectedly low. Try to set the environment variable GPU_SINGLE_ALLOC_PERCENT.
[2018-03-26 21:00:43] : AMD: GPU configuration stored in file 'amd.txt'
[2018-03-26 21:00:43] : Compiling code and initializing GPUs. This will take a while...
[2018-03-26 21:00:43] : WARNING: using non AMD device: Apple
[2018-03-26 21:00:43] : Device 0 work size 8 / 32.

<b>[2018-03-26 21:00:43] : OpenCL device 0 - Precompiled code /var/root/.openclcache/b97f203fe61b1b7b1af87c8fdab7b8756aa712020e6232757879d481bf9fcccd.openclbin not found. Compiling ...
[2018-03-26 21:00:43] : Error CL_BUILD_PROGRAM_FAILURE when calling clBuildProgram.
Build log:
<program source>:160:7: warning: no previous prototype for function 'AES_Round'
uint4 AES_Round(const __local uint *AES0, const __local uint *AES1, const __local uint *AES2, const __local uint *AES3, const uint4 X, uint4 key)
      ^
<program source>:221:7: warning: no previous prototype for function 'SKEIN_ROT'
ulong SKEIN_ROT(const uint2 x, const uint y)
      ^
<program source>:227:6: warning: no previous prototype for function 'SkeinMix8'
void SkeinMix8(ulong4 *pv0, ulong4 *pv1, const ulong4 rc)
     ^
<program source>:237:8: warning: no previous prototype for function 'SkeinEvenRound'
ulong8 SkeinEvenRound(ulong8 p, const ulong8 h, const ulong *t, const uint s, const uint q)
       ^
<program source>:258:8: warning: no previous prototype for function 'SkeinOddRound'
ulong8 SkeinOddRound(ulong8 p, const ulong8 h, const ulong *t, const uint s, const uint q)
       ^
<program source>:279:8: warning: no previous prototype for function 'Skein512Block'
ulong8 Skein512Block(ulong8 p, ulong8 h, ulong h8, const ulong *t)
       ^
<program source>:1028:6: warning: no previous prototype for function 'keccakf1600'
void keccakf1600(ulong *s)
     ^
<program source>:1088:6: warning: no previous prototype for function 'keccakf1600_1'
void keccakf1600_1(ulong *st)
     ^
<program source>:1147:6: warning: no previous prototype for function 'keccakf1600_2'
void keccakf1600_2(ulong *st)
     ^
<program source>:1277:6: warning: no previous prototype for function 'CNKeccak'
void CNKeccak(ulong *output, ulong *input)
     ^
<program source>:1305:6: warning: no previous prototype for function 'AESExpandKey256'
void AESExpandKey256(uint *keybuf)
     ^
<program source>:1337:46: error: parameter may not be qualified with an address space
inline uint4 mix_and_propagate(__local uint4 xin[8][WORKSIZE])
                                             ^

[2018-03-26 21:00:43] : WARNING: AMD device not found
[2018-03-26 21:00:43] : WARNING: backend AMD disabled.</b>

[2018-03-26 21:00:43] : CPU configuration stored in file 'cpu.txt'
[2018-03-26 21:00:43] : WARNING on macOS thread affinity is only advisory.
[2018-03-26 21:00:43] : Starting 1x thread, affinity: 0.
[2018-03-26 21:00:43] : hwloc: set_thisthread_membind not supported
[2018-03-26 21:00:43] : WARNING on macOS thread affinity is only advisory.
[2018-03-26 21:00:43] : Starting 1x thread, affinity: 2.
[2018-03-26 21:00:43] : hwloc: set_thisthread_membind not supported
[2018-03-26 21:00:43] : WARNING on macOS thread affinity is only advisory.
[2018-03-26 21:00:43] : Starting 1x thread, affinity: 4.
[2018-03-26 21:00:43] : hwloc: set_thisthread_membind not supported
[2018-03-26 21:00:43] : WARNING on macOS thread affinity is only advisory.
[2018-03-26 21:00:43] : Starting 1x thread, affinity: 6.
[2018-03-26 21:00:43] : hwloc: set_thisthread_membind not supported
[2018-03-26 21:00:43] : Fast-connecting to 192.168.20.214:3333 pool ...
[2018-03-26 21:00:43] : Pool 192.168.20.214:3333 connected. Logging in...
[2018-03-26 21:00:44] : Difficulty changed. Now: 500.
[2018-03-26 21:00:44] : Pool logged in.
[2018-03-26 21:00:55] : Result accepted by the pool.
[2018-03-26 21:00:56] : Result accepted by the pool.
```

**Comment by psychocrypt** [comment]
The warning during the compile should be fixed with #1240

Maybe this solved also compile issue but I am not sure.

**Comment by djfinch** [comment]
Thank you. Now compiled without issues. Anyway, CL backend is still not working. CL compiler throwing 
errors with pre-compile. Should be these prototypes somewhere in headers?
```
[2018-03-27 23:09:16] : Error CL_BUILD_PROGRAM_FAILURE when calling clBuildProgram.
Build log:
<program source>:158:7: warning: no previous prototype for function 'AES_Round'
uint4 AES_Round(const __local uint *AES0, const __local uint *AES1, const __local uint *AES2, const __local uint *AES3, const uint4 X, uint4 key)
      ^
<program source>:219:7: warning: no previous prototype for function 'SKEIN_ROT'
ulong SKEIN_ROT(const uint2 x, const uint y)
      ^
<program source>:225:6: warning: no previous prototype for function 'SkeinMix8'
void SkeinMix8(ulong4 *pv0, ulong4 *pv1, const ulong4 rc)
     ^
<program source>:235:8: warning: no previous prototype for function 'SkeinEvenRound'
ulong8 SkeinEvenRound(ulong8 p, const ulong8 h, const ulong *t, const uint s, const uint q)
       ^
<program source>:256:8: warning: no previous prototype for function 'SkeinOddRound'
ulong8 SkeinOddRound(ulong8 p, const ulong8 h, const ulong *t, const uint s, const uint q)
       ^
<program source>:277:8: warning: no previous prototype for function 'Skein512Block'
ulong8 Skein512Block(ulong8 p, ulong8 h, ulong h8, const ulong *t)
       ^
<program source>:1026:6: warning: no previous prototype for function 'keccakf1600'
void keccakf1600(ulong *s)
     ^
<program source>:1086:6: warning: no previous prototype for function 'keccakf1600_1'
void keccakf1600_1(ulong *st)
     ^
<program source>:1145:6: warning: no previous prototype for function 'keccakf1600_2'
void keccakf1600_2(ulong *st)
     ^
<program source>:1275:6: warning: no previous prototype for function 'CNKeccak'
void CNKeccak(ulong *output, ulong *input)
     ^
<program source>:1303:6: warning: no previous prototype for function 'AESExpandKey256'
void AESExpandKey256(uint *keybuf)
     ^
<program source>:1335:46: error: parameter may not be qualified with an address space
inline uint4 mix_and_propagate(__local uint4 xin[8][WORKSIZE])
                                             ^
```

**Comment by psychocrypt** [comment]
the strange thing is that all te functions are defined before they will be
used.
Only if you empty the .cl filed in the amd backend will create suche an
issue.

**Comment by djfinch** [comment]
Yep, it's very strange. I just cloned master, nothing changed within the files. I can see them there: [L833](https://github.com/fireice-uk/xmr-stak/blob/master/xmrstak/backend/amd/amd_gpu/gpu.cpp#L833) : but not sure why they acting as non-included/defined. :(

**Comment by creaktive** [comment]
I have exactly the same issue o/

**Comment by psychocrypt** [comment]
Please checkout https://github.com/psychocrypt/xmr-stak/tree/topic-testOSXAMD23 or download the branch direct https://github.com/psychocrypt/xmr-stak/archive/topic-testOSXAMD23.zip

Compile this branch and run it. The miner will create a file `amd.cl` please post this file to pastbin.com ans share a link here.

**Comment by djfinch** [comment]
Hello @psychocrypt ,

Thanks for your effort. Compiled from your repo and miner runs flawlesly  incl. OpenCL part but I can't find amd.cl file... Should be stored inside stak basedir or elsewhere?

**Comment by psychocrypt** [comment]
stak base dir. Could you please post the output.

djfinch <notifications@github.com> schrieb am Fr., 30. März 2018, 22:27:

**Comment by psychocrypt** [comment]
do you started amd mining? Du you compiled the correct branch?

**Comment by psychocrypt** [comment]
I updated the branch again, now it should be possible to mine with AMD under OSX. If you use git check with `git log` if the following commit is the newest.

```
commit f92eae2354b469176ba18828561f20c7f9dc60e8
Author: psychocrypt <psychocryptHPC@gmail.com>
Date:   Fri Mar 30 22:52:39 2018 +0200

    fix shared mem access OSX
```

**Comment by djfinch** [comment]
This one works. Precompiled code not found --> compiler created one,, then ran the miner and all works. I did some manual fine-tune of amd.txt and now i'm getting around 20% higher hashrate than from 2.2.0 with the same config!!! AWESOME!

@everyone:
```
git clone --branch topic-testOSXAMD23 https://github.com/psychocrypt/xmr-stak.git xmr-stak-debug
```

here is amd.cl - https://pastebin.com/gkWvjv2N

**Comment by psychocrypt** [comment]
ok I will add this fix to our dev, than it will go into the next release

**Comment by djfinch** [comment]
Perfect. Thank you!
