### ISSUE TITLE
WINDOWS 10 Compilation: LINK : fatal error C1900: Il mismatch between 'P1' version '20161212' and 'P2' version '20150812'

### ISSUE THREAD

**Issue by DrOctavius** [fireice-uk/xmr-stak#211]
LINK : fatal error C1900: Il mismatch between 'P1' version '20161212' and 'P2' version '20150812'

"C:\Users\USERr\Desktop\xmr\xmr-stak\xmr-stak\build\install.vcxproj" (default target) (1) ->
"C:\Users\USER\Desktop\xmr\xmr-stak\xmr-stak\build\ALL_BUILD.vcxproj" (default target) (3) ->
"C:\Users\USER\Desktop\xmr\xmr-stak\xmr-stak\build\xmrstak_cuda_backend.vcxproj" (default target) (7) ->
(CustomBuild target) ->
  C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 1. [C:\Users\USER\Desktop\xm
r\xmr-stak\xmr-stak\build\xmrstak_cuda_backend.vcxproj]

"C:\Users\USER\Desktop\xmr\xmr-stak\xmr-stak\build\install.vcxproj" (default target) (1) ->
"C:\Users\USER\Desktop\xmr\xmr-stak\xmr-stak\build\ALL_BUILD.vcxproj" (default target) (3) ->
"C:\Users\USER\Desktop\xmr\xmr-stak\xmr-stak\build\xmrstak_opencl_backend.vcxproj" (default target) (8) ->
(Link target) ->
  LINK : fatal error C1900: Il mismatch between 'P1' version '20161212' and 'P2' version '20150812' [C:\Users\USER\Desktop\xmr\xmr-stak\xmr-stak\build\xmrstak_open
cl_backend.vcxproj]
  LINK : fatal error LNK1257: code generation failed [C:\Users\USER\Desktop\xmr\xmr-stak\xmr-stak\build\xmrstak_opencl_backend.vcxproj]

 45 Warning(s)
    5 Error(s)

**Comment by psychocrypt** [comment]
If you compile with v140 than you need to download xmr-stak-dep for cuda8
else for cuda 9. please see the compile guide.

**Comment by DrOctavius** [comment]
Well...yes i did step by step many times... i have CUDA 9
Downloaded the specific xmr-stak-dep and urchived...

..../cmake -G "Visual Studio 15 2017 Win64" -T v141,host=x64 ..
-- The C compiler identification is MSVC 19.10.25019.0
-- The CXX compiler identification is MSVC 19.10.25019.0
-- Check for working C compiler: D:/ProgramFiles/VS/VC/Tools/MSVC/14.10.25017/bin/HostX64/x64/cl.exe
-- Check for working C compiler: D:/ProgramFiles/VS/VC/Tools/MSVC/14.10.25017/bin/HostX64/x64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: D:/ProgramFiles/VS/VC/Tools/MSVC/14.10.25017/bin/HostX64/x64/cl.exe
-- Check for working CXX compiler: D:/ProgramFiles/VS/VC/Tools/MSVC/14.10.25017/bin/HostX64/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Set miner currency to 'monero' and 'aeon'
-- Found CUDA: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0 (found suitable version "9.0", minimum required is "7.5")
-- Looking for CL_VERSION_2_0
-- Looking for CL_VERSION_2_0 - found
-- Found OpenCL: C:/Program Files (x86)/AMD APP SDK/3.0/lib/x86_64/OpenCL.lib (found version "2.0")
-- Found OpenSSL: C:/Users/USER/Desktop/xmr/xmr-stak/xmr-stak/openssl/lib/libeay32.lib (found version "1.0.2m")
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/USER/Desktop/xmr/xmr-stak/xmr-stak/build

**Comment by SlaytanicPB** [comment]
I got the same problem.  I couldn't get the code to compile with Cuda 9 and the -T v141 flag.  I have been banging my head for about 2 days trying to figure out what the problem is.  Every time I used the -T v141 flag, I'd get an error saying cmake built it with a different version than the one I'm trying to run, and to delete the CMakeCache.txt file and CMakeFiles directory.

I gave up trying to build with Cuda 9, as I won't be using it in the near future.  So I just followed the rest of the built instructions and it worked fine.  Also, I should add that I built the CMakeCache.txt and CMakeFiles directory using cmake-gui.exe for both with and without Cuda 9.

**Comment by SlaytanicPB** [comment]
I see someone posted this error message that I always got when trying to compile with Cuda 9

cmake -G "Visual Studio 15 2017 Win64" -T v141,host=x64 ..
CMake Error: Error: generator : Visual Studio 15 2017 Win64
Does not match the generator used previously: Visual Studio 15 2017
Either remove the CMakeCache.txt file and CMakeFiles directory or choose a different binary directory.

It would be nice to know where in CMakeCache.txt where it writes down the version of Visual Studio used.  Also, do you know how to check on the command line what version of Visual Studio is called on when VsMSBuildCmd.bat is run?

**Comment by DrOctavius** [comment]
@SlaytanicPB Hey
Version of VS (Version : 15.0.26430.16):

C:\Users\mrdiffer>D:\ProgramFiles\VS\Common7\Tools\VsMSBuildCmd.bat -help
.
** Visual Studio "15" Developer Command Prompt Help **
** Version : 15.0.26430.16
.
Syntax: vsdevcmd.bat [options]
[options] :
    -arch=architecture : Architecture for compiled binaries/libraries
           * x86 [default]
           * amd64
           * arm
    -host_arch=architecture : Architecture of compiler binaries
           * x86 [default]
           * amd64
    -winsdk=version : Version of Windows SDK to select.
           ** 10.0.xxyyzz.0 : Windows 10 SDK (e.g 10.0.10240.0)
                              [default : Latest Windows 10 SDK]
           ** 8.1 : Windows 8.1 SDK
           ** none : Do not setup Windows SDK variables.
                     For use with build systems that prefer to
                     determine Windows SDK version independently.
    -app_platform=platform : Application Platform Target Type.
           ** Desktop : Classic Win32 Apps          [default]
           ** UWP : Universal Windows Platform Apps
    -no_ext : Only scripts from [VS150COMNTOOLS]\VsDevCmd\Core
              directory are run during initialization.
    -no_logo : Suppress printing of the developer command prompt banner.
    -test : Run smoke tests to verify environment integrity after
            after initialization (requires all other arguments
            to be the same other than -test).
    -help : prints this help message.


#==========================================#

Another thing i tried to compile without -T v141 

cmake -G "Visual Studio 15 2017 Win64" ..
AND
cmake -G "Visual Studio 15 2017 Win64" cmake -G "Visual Studio 15 2017 Win64" -T host=x64  ..

And same errors...

#==========================================#

Removed folder "CMakeFiles" after cmake -G "Visual Studio 15 2017 Win64" -T v141,host=x64 ..
AND started again : cmake --build . --config Release --target install

And same errors....

**Comment by SlaytanicPB** [comment]
I've tried to compile again, just to see if I can figure it out. However, I haven't programed in decades, so I'm not sure about what I'm looking at or how to fix it.

I did however find something, so I don't know if this will lead to a fix or not.
When running cmake-gui.exe and looking at the configuration I noticed this...
CUDA_HOST_COMPILER  was set to
C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.11.25503/bin/Hostx86/x64/cl.exe

I'm not sure why it isn't set to this...
C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.11.25503/bin/Hostx64/x64/cl.exe

Also, when I clicked on the Open Project button and it opens Visual Studio I noticed a few things when I tried to build the project.  First, as it's compiling the code an error pops up about external dependencies and it gives me 4 options - Reload, Reload All, Ignore, Ignore All.
I tried reload, and tried to compile the code again.
This time the compile came up with an error with cuda_core.cu line 171
__launch_bounds__( XMR_STAK_THREADS * 4 )
When I hover the mouse over __launch_bounds__  I see what it's hanging on, it's this...
this declaration has no storage class or type specifier

I hope this helps...

**Comment by psychocrypt** [comment]
The launch bounds are fixed in the dev branch. Please keep in CMake the
paramter zero to avoid compile issues.
Please post the commands used to compile and the output to see whats
happened with the selected compiler.

**Comment by SlaytanicPB** [comment]
Well, I made some progress, but the build still failed.  I got past this problem...

cmake -G "Visual Studio 15 2017 Win64" -T v141,host=x64 ..
CMake Error: Error: generator : Visual Studio 15 2017 Win64
Does not match the generator used previously: Visual Studio 15 2017
Either remove the CMakeCache.txt file and CMakeFiles directory or choose a different binary directory.

I did it by starting VsMSBuildCmd.bat like this...
VsMSBuildCmd.bat -ARCH=amd64 -HOST_ARCH=amd64

So then I was able to use this command - cmake --build . --config Release --target install
The code was compiling, I was thinking YES!!  Then I saw this...

 C:/xmr-stak-2.0.0/xmrstak/backend/nvidia/nvcc_code/cuda_core.cu(11): error : identifier "waitTime" is undefined [C:\xmr-stak-2.0.0\build\xmrstak_cuda_backend.vcxproj]
  C:/xmr-stak-2.0.0/xmrstak/backend/nvidia/nvcc_code/cuda_core.cu(13): error : identifier "waitTime" is undefined [C:\xmr-stak-2.0.0\build\xmrstak_cuda_backend.vcxproj]
  C:/xmr-stak-2.0.0/xmrstak/backend/nvidia/nvcc_code/cuda_core.cu(324): error : too few arguments in function call [C:\xmr-stak-2.0.0\build\xmrstak_cuda_backend.vcxproj]
  C:/xmr-stak-2.0.0/xmrstak/backend/nvidia/nvcc_code/cuda_core.cu(326): error : too few arguments in function call [C:\xmr-stak-2.0.0\build\xmrstak_cuda_backend.vcxproj]
  C:/xmr-stak-2.0.0/xmrstak/backend/nvidia/nvcc_code/cuda_core.cu(236): error : expected a ")" [C:\xmr-stak-2.0.0\build\xmrstak_cuda_backend.vcxproj]
  C:/xmr-stak-2.0.0/xmrstak/backend/nvidia/nvcc_code/cuda_core.cu(343): error : too few arguments in function call [C:\xmr-stak-2.0.0\build\xmrstak_cuda_backend.vcxproj]
  C:/xmr-stak-2.0.0/xmrstak/backend/nvidia/nvcc_code/cuda_core.cu(324): error : too few arguments in function call [C:\xmr-stak-2.0.0\build\xmrstak_cuda_backend.vcxproj]
  C:/xmr-stak-2.0.0/xmrstak/backend/nvidia/nvcc_code/cuda_core.cu(326): error : too few arguments in function call [C:\xmr-stak-2.0.0\build\xmrstak_cuda_backend.vcxproj]
  C:/xmr-stak-2.0.0/xmrstak/backend/nvidia/nvcc_code/cuda_core.cu(236): error : expected a ")" [C:\xmr-stak-2.0.0\build\xmrstak_cuda_backend.vcxproj]
  C:/xmr-stak-2.0.0/xmrstak/backend/nvidia/nvcc_code/cuda_core.cu(343): error : too few arguments in function call [C:\xmr-stak-2.0.0\build\xmrstak_cuda_backend.vcxproj]

I tried running the .exe the compiled made and got this error, which I expected...
WARNING: NVIDIA cannot load backend library: xmrstak_cuda_backend.dll
WARNING: NVIDIA Backend disabled

**Comment by SlaytanicPB** [comment]
Ok, I messed up, I thought I copied the latest version of cuda_core.cu into the right dir.  Finally, I was able to build it and got no errors about the xmrstak_cuda_backend.dll on startup.

So starting VsMSBuildCmd.bat without any options puts it into x86 by default and by adding
-ARCH=amd64 -HOST_ARCH=amd64
fixed it for me.  I was able to use the rest of the instructions for Cuda 9 and build it.

**Comment by Njeroe** [comment]
```
C:\xmr-stak-dev\xmr-stak-dev\build>cmake -G "Visual Studio 15 2017 Win64" -T v140,host=x64 ..
-- The C compiler identification is MSVC 19.0.24225.1
-- The CXX compiler identification is MSVC 19.0.24225.1
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Set miner currency to 'monero' and 'aeon'
-- Found CUDA: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0 (found suitable version "8.0", minimum required is "7.5")
-- Looking for CL_VERSION_2_0
-- Looking for CL_VERSION_2_0 - found
-- Found OpenCL: C:/Program Files (x86)/AMD APP SDK/3.0/lib/x86_64/OpenCL.lib (found version "2.0")
-- Found OpenSSL: C:/xmr-stak-dep/openssl/lib/libeay32.lib (found version "1.0.2m")
-- Configuring done
-- Generating done
-- Build files have been written to: C:/xmr-stak-dev/xmr-stak-dev/build

"C:\xmr-stak-dev\xmr-stak-dev\build\install.vcxproj" (default target) (1) ->
"C:\xmr-stak-dev\xmr-stak-dev\build\ALL_BUILD.vcxproj" (default target) (3) ->
"C:\xmr-stak-dev\xmr-stak-dev\build\xmr-stak.vcxproj" (default target) (4) ->
(Link target) ->
  LINK : fatal error C1900: Il mismatch between 'P1' version '20161212' and 'P2' version '20150812' [C:\xmr-stak-dev\xm
r-stak-dev\build\xmr-stak.vcxproj]
  LINK : fatal error LNK1257: code generation failed [C:\xmr-stak-dev\xmr-stak-dev\build\xmr-stak.vcxproj]


"C:\xmr-stak-dev\xmr-stak-dev\build\install.vcxproj" (default target) (1) ->
"C:\xmr-stak-dev\xmr-stak-dev\build\ALL_BUILD.vcxproj" (default target) (3) ->
"C:\xmr-stak-dev\xmr-stak-dev\build\xmrstak_cuda_backend.vcxproj" (default target) (7) ->
  LINK : fatal error C1900: Il mismatch between 'P1' version '20161212' and 'P2' version '20150812' [C:\xmr-stak-dev\xm
r-stak-dev\build\xmrstak_cuda_backend.vcxproj]
  LINK : fatal error LNK1257: code generation failed [C:\xmr-stak-dev\xmr-stak-dev\build\xmrstak_cuda_backend.vcxproj]


"C:\xmr-stak-dev\xmr-stak-dev\build\install.vcxproj" (default target) (1) ->
"C:\xmr-stak-dev\xmr-stak-dev\build\ALL_BUILD.vcxproj" (default target) (3) ->
"C:\xmr-stak-dev\xmr-stak-dev\build\xmrstak_opencl_backend.vcxproj" (default target) (8) ->
  LINK : fatal error C1900: Il mismatch between 'P1' version '20161212' and 'P2' version '20150812' [C:\xmr-stak-dev\xm
r-stak-dev\build\xmrstak_opencl_backend.vcxproj]
  LINK : fatal error LNK1257: code generation failed [C:\xmr-stak-dev\xmr-stak-dev\build\xmrstak_opencl_backend.vcxproj
]

    77 Warning(s)
    6 Error(s)
```

I have the same issue, and yes I downloaded the cuda8 xmr-stak-dep...

**Comment by fireice-uk** [comment]
Should be fixed now. Please reopen if not.

**Comment by omomthings** [comment]
Hello there,
The problem is still here, having the exact same trace as Njeroe on his last comment.
I countered the problem with these options : 
- VsMSBuildCmd.bat -arch=amd64 -host_arch=amd64
-Downloaded the original hwloc files and replaced the xmr-stak-dep with these (till this point I reduced the number of errors  from 6 to 2 )
-  cmake -G "Visual Studio 15 2017 Win64" -T v141,host=x64 .. -DOpenCL_ENABLE=OFF -DMICROHTTPD_ENABLE=OFF (notice i'm building for Cuda 9 (I have Cuda 9.1) with -T v141)

Build ok for me, but still can't get it to work with my nvidia... but that's for another thread..

**Comment by KyferEz** [comment]
I am also having this issue with latest Master and Dev branches. Exact same issues. My cmake and build commands are the same from this page for CUDA 9: https://github.com/fireice-uk/xmr-stak/blob/master/doc/compile_Windows.md

Pleasse Reopen!
