### ISSUE TITLE
Some problem on version 2.10

### ISSUE THREAD

**Issue by nhnc** [fireice-uk/xmr-stak#2330]
I have update my miner from 2.5 to 2.10, and I found some problems.

1. The setting of "low_power_mode" in the cpu.txt seems not work. For example, one of my CPU is i7-5930k, that is 6 cores with 15M cache. In the old version, I set up the low_power_mode "true" will improve hashrate significantly. But that is no difference in the new version when I doubled the cache of one core.

2. For some very old CPU, such as Xeon X5355 or Pentium D, the "asm" setting in the cpu.txt needs be forced to off, or it will show "Illegal instruction (core dumped)". And set to off also reduce the hashrate about 50%.  Is this related to AES?

**Comment by Spudz76** [comment]
both issues were patched with release 2.10.1 (are you still on 2.10.0?)

**Comment by nhnc** [comment]
Yes, I will try 2.10.1, thanks you.

**Comment by nhnc** [comment]
I have tried 2.10.1, but the low_power_mode still not work when I mining monreo on i7-5930k.
The auto setting of  asm seems OK. But that still very slow on X5355. The hashrate reduced about 50% from 2.5

**Comment by cmlau** [comment]
I am mining Monero and my CPU is i9-9900K. I use 4 cores only when using low power mode since CPU has 16M L3 cache.

For 2.8 version:
Without low power mode: around 80 for each core
With low power mode: around 140 for each core.

For 2.10.0 version:
Without low power mode: around 80 for each core
With low power mode: around 80 for each core.

For 2.10.1 version:
Without low power mode: around 80 for each core
With low power mode: around 95-100 for each core.

Is the new algo itself cannot  provide as much efficiency as old algo when using the low power mode?

**Comment by Spudz76** [comment]
CN-R has different actions in it than CN-V8, so it did shake up performances again but not as much as CN-V7 to V8 fork did.  I have noticed it hurts older CPUs more (up to 50% is correct, but some of mine only lost like 30% depending on core type and compiler and cache size), and newer ones almost no reduction (maybe 7% avg).  The hashrate also seems to vary a bit which is by design (self-morphing algo changes every so often on new-block, random actions added or removed change the overall efficiency for that round, etc).

There could be more optimization possible for lesser CPUs on CN-R but I think there are other todos ahead of it.

I have been considering switching all my old-CPU rigs to some other easier coin (turtle?) but the profit doesn't outweigh the triple hashrate so it's kind of pointless other than seeing a high hashrate onscreen again.

I do not know about the low_power_mode I have never had positive gain from trying it 2.5 or 2.10 or otherwise, and I have a few large cache CPUs (xeon) where it should do something.

**Comment by Spudz76** [comment]
Appears as though we do not have [these enhancements](https://github.com/xmrig/xmrig/commit/488cec09dd30cd51e22aff68cd7e642a19dc8d51) yet but the increase looks about like what we're missing

Test with xmrig and see how it does on the old CPUs, I may do the same

**Comment by Spudz76** [comment]
Confirm switching to xmrig doubled or better all my old CPUs (same CN-R algo)

**Comment by thrxpl** [comment]
have similar prblm
after upgrade from 2.10.0 to 2.10.1 I have a big hash drop: from about 450h/s to about 100h/s. Mining on the Xeon X5670 @2.93GHz 24 cores cpu. Any ideas?

**Comment by nhnc** [comment]
> Confirm switching to xmrig doubled or better all my old CPUs (same CN-R algo)

I also confirmed my old CPU Xeon X5355 performed well by xmrig-2.14.1, as the xmr-stak-2.5.0.
However, the swich of low power mode with i7-5930k also have no significant change in the xmrig-2.14.1. So, is that the  general problem with new algorithm?

**Comment by psychocrypt** [comment]
if this cpu has avx support this issue should be fixed with 2.10.1

**Comment by Spudz76** [comment]
The half of the issue about old CPU speeds on CN-R is not solved at all

I have jumped ship to xmrig for my old CPUs until @SChernykh or someone applies their 2.6x speedup code here.

**Comment by migonr77** [comment]
Hi, problem with multihash is not solved for me on linux. 

Here are results with multi hash on two cpu threads: 

[2019-03-13 11:13:23] : Mining coin: cryptonight_r
[2019-03-13 11:13:23] : Starting 2x thread, affinity: 2.
[2019-03-13 11:13:23] : hwloc: memory pinned
[2019-03-13 11:13:23] : Starting 1x thread, affinity: 3.
[2019-03-13 11:13:23] : hwloc: memory pinned
[2019-03-13 11:13:23] : Starting 1x thread, affinity: 4.
[2019-03-13 11:13:23] : hwloc: memory pinned
[2019-03-13 11:13:23] : Starting 1x thread, affinity: 5.
[2019-03-13 11:13:23] : hwloc: memory pinned
[2019-03-13 11:13:23] : Starting 2x thread, affinity: 8.
[2019-03-13 11:13:23] : hwloc: memory pinned
[2019-03-13 11:13:23] : Starting 1x thread, affinity: 9.
[2019-03-13 11:13:23] : hwloc: memory pinned
[2019-03-13 11:13:23] : Starting 1x thread, affinity: 10.
[2019-03-13 11:13:23] : hwloc: memory pinned
[2019-03-13 11:13:23] : Starting 1x thread, affinity: 11.
[2019-03-13 11:13:23] : hwloc: memory pinned
[2019-03-13 11:13:23] : Fast-connecting to pool.supportxmr.com:9000 pool ...
[2019-03-13 11:13:23] : TLS fingerprint [pool.supportxmr.com:9000] 
[2019-03-13 11:13:23] : Pool pool.supportxmr.com:9000 connected. Logging in...
[2019-03-13 11:13:23] : Difficulty changed. Now: 20000.
[2019-03-13 11:13:23] : Pool logged in.
[2019-03-13 11:13:23] : enable cryptonight_r asm 'intel_avx' cpu's
[2019-03-13 11:13:23] : enable cryptonight_r asm 'intel_avx' cpu's
[2019-03-13 11:13:23] : enable cryptonight_r asm 'intel_avx' cpu's
[2019-03-13 11:13:23] : enable cryptonight_r asm 'intel_avx' cpu's
[2019-03-13 11:13:23] : enable cryptonight_r asm 'intel_avx' cpu's
[2019-03-13 11:13:23] : enable cryptonight_r asm 'intel_avx' cpu's
[2019-03-13 11:13:23] : enable cryptonight_r asm 'intel_avx' cpu's
[2019-03-13 11:13:23] : enable cryptonight_r asm 'intel_avx' cpu's
...
[2019-03-13 11:16:08] : Result accepted by the pool.
HASHRATE REPORT - CPU
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 |   37.6 |   35.3 |   (na) |  1 |   41.5 |   40.4 |   (na) |
|  2 |   42.1 |   41.0 |   (na) |  3 |   41.6 |   40.5 |   (na) |
|  4 |   37.1 |   35.2 |   (na) |  5 |   39.9 |   39.7 |   (na) |
|  6 |   41.9 |   42.1 |   (na) |  7 |   42.3 |   41.9 |   (na) |
Totals (CPU):   324.0  316.1    0.0 H/s
-----------------------------------------------------------------
Totals (ALL):    324.0  316.1    0.0 H/s
Highest:   342.6 H/s
-----------------------------------------------------------------

and the same cfg without multihash:

[2019-03-13 11:11:38] : Mining coin: cryptonight_r
[2019-03-13 11:11:38] : Starting 1x thread, affinity: 2.
[2019-03-13 11:11:38] : hwloc: memory pinned
[2019-03-13 11:11:38] : Starting 1x thread, affinity: 3.
[2019-03-13 11:11:38] : hwloc: memory pinned
[2019-03-13 11:11:38] : Starting 1x thread, affinity: 4.
[2019-03-13 11:11:38] : hwloc: memory pinned
[2019-03-13 11:11:38] : Starting 1x thread, affinity: 5.
[2019-03-13 11:11:38] : hwloc: memory pinned
[2019-03-13 11:11:38] : Starting 1x thread, affinity: 8.
[2019-03-13 11:11:38] : hwloc: memory pinned
[2019-03-13 11:11:38] : Starting 1x thread, affinity: 9.
[2019-03-13 11:11:38] : hwloc: memory pinned
[2019-03-13 11:11:38] : Starting 1x thread, affinity: 10.
[2019-03-13 11:11:38] : hwloc: memory pinned
[2019-03-13 11:11:38] : Starting 1x thread, affinity: 11.
[2019-03-13 11:11:38] : hwloc: memory pinned
[2019-03-13 11:11:38] : Fast-connecting to pool.supportxmr.com:9000 pool ...
[2019-03-13 11:12:02] : TLS fingerprint [pool.supportxmr.com:9000] 
[2019-03-13 11:12:02] : Pool pool.supportxmr.com:9000 connected. Logging in...
[2019-03-13 11:12:03] : Difficulty changed. Now: 20000.
[2019-03-13 11:12:03] : Pool logged in.
[2019-03-13 11:12:03] : enable cryptonight_r asm 'intel_avx' cpu's
[2019-03-13 11:12:03] : enable cryptonight_r asm 'intel_avx' cpu's
[2019-03-13 11:12:03] : enable cryptonight_r asm 'intel_avx' cpu's
[2019-03-13 11:12:03] : enable cryptonight_r asm 'intel_avx' cpu's
[2019-03-13 11:12:03] : enable cryptonight_r asm 'intel_avx' cpu's
[2019-03-13 11:12:03] : enable cryptonight_r asm 'intel_avx' cpu's
[2019-03-13 11:12:03] : enable cryptonight_r asm 'intel_avx' cpu's
[2019-03-13 11:12:03] : enable cryptonight_r asm 'intel_avx' cpu's
-----------------------------------------------------------------
HASHRATE REPORT - CPU
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 |   41.3 |   41.6 |   (na) |  1 |   41.8 |   42.1 |   (na) |
|  2 |   42.7 |   42.9 |   (na) |  3 |   42.5 |   42.6 |   (na) |
|  4 |   41.2 |   40.1 |   (na) |  5 |   38.4 |   40.5 |   (na) |
|  6 |   39.6 |   42.3 |   (na) |  7 |   40.8 |   41.8 |   (na) |
Totals (CPU):   328.2  333.8    0.0 H/s
-----------------------------------------------------------------
Totals (ALL):    328.2  333.8    0.0 H/s
Highest:   354.2 H/s
-----------------------------------------------------------------
HASHRATE REPORT - CPU
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 |   41.8 |   41.6 |   (na) |  1 |   42.2 |   42.1 |   (na) |
|  2 |   43.1 |   43.0 |   (na) |  3 |   42.7 |   42.7 |   (na) |
|  4 |   42.3 |   40.0 |   (na) |  5 |   42.9 |   40.5 |   (na) |
|  6 |   43.1 |   42.3 |   (na) |  7 |   44.0 |   41.8 |   (na) |
Totals (CPU):   342.1  333.9    0.0 H/s
-----------------------------------------------------------------
Totals (ALL):    342.1  333.9    0.0 H/s
Highest:   354.2 H/s
-----------------------------------------------------------------
CPU is 2x Intel(R) Xeon(R) CPU E5-2640 0 @ 2.50GHz
Tested on 6 servers with the same config.

Thanx.

migo
