### ISSUE TITLE
Build issues on Alpine in Docker

### ISSUE THREAD

**Issue by Rich7690** [fireice-uk/xmr-stak#2640]
Attempting a dockerized build and getting the following:

```
Scanning dependencies of target xmr-stak-randomx
[  2%] Building CXX object CMakeFiles/xmr-stak-randomx.dir/xmrstak/backend/cpu/crypto/randomx/aes_hash.cpp.o
[  4%] Building CXX object CMakeFiles/xmr-stak-randomx.dir/xmrstak/backend/cpu/crypto/randomx/allocator.cpp.o
[  6%] Building C object CMakeFiles/xmr-stak-randomx.dir/xmrstak/backend/cpu/crypto/randomx/argon2_core.c.o
[  8%] Building C object CMakeFiles/xmr-stak-randomx.dir/xmrstak/backend/cpu/crypto/randomx/argon2_ref.c.o
[ 10%] Building CXX object CMakeFiles/xmr-stak-randomx.dir/xmrstak/backend/cpu/crypto/randomx/blake2_generator.cpp.o
[ 13%] Building C object CMakeFiles/xmr-stak-randomx.dir/xmrstak/backend/cpu/crypto/randomx/blake2/blake2b.c.o
[ 15%] Building CXX object CMakeFiles/xmr-stak-randomx.dir/xmrstak/backend/cpu/crypto/randomx/bytecode_machine.cpp.o
[ 17%] Building CXX object CMakeFiles/xmr-stak-randomx.dir/xmrstak/backend/cpu/crypto/randomx/dataset.cpp.o
[ 19%] Building CXX object CMakeFiles/xmr-stak-randomx.dir/xmrstak/backend/cpu/crypto/randomx/instructions_portable.cpp.o
[ 21%] Building CXX object CMakeFiles/xmr-stak-randomx.dir/xmrstak/backend/cpu/crypto/randomx/randomx.cpp.o
[ 23%] Building C object CMakeFiles/xmr-stak-randomx.dir/xmrstak/backend/cpu/crypto/randomx/reciprocal.c.o
[ 26%] Building CXX object CMakeFiles/xmr-stak-randomx.dir/xmrstak/backend/cpu/crypto/randomx/soft_aes.cpp.o
[ 28%] Building CXX object CMakeFiles/xmr-stak-randomx.dir/xmrstak/backend/cpu/crypto/randomx/superscalar.cpp.o
[ 30%] Building CXX object CMakeFiles/xmr-stak-randomx.dir/xmrstak/backend/cpu/crypto/randomx/virtual_machine.cpp.o
[ 32%] Building CXX object CMakeFiles/xmr-stak-randomx.dir/xmrstak/backend/cpu/crypto/randomx/virtual_memory.cpp.o
[ 34%] Building CXX object CMakeFiles/xmr-stak-randomx.dir/xmrstak/backend/cpu/crypto/randomx/vm_compiled_light.cpp.o
[ 36%] Building CXX object CMakeFiles/xmr-stak-randomx.dir/xmrstak/backend/cpu/crypto/randomx/vm_compiled.cpp.o
[ 39%] Building CXX object CMakeFiles/xmr-stak-randomx.dir/xmrstak/backend/cpu/crypto/randomx/vm_interpreted_light.cpp.o
[ 41%] Building CXX object CMakeFiles/xmr-stak-randomx.dir/xmrstak/backend/cpu/crypto/randomx/vm_interpreted.cpp.o
[ 43%] Building C object CMakeFiles/xmr-stak-randomx.dir/xmrstak/backend/cpu/crypto/randomx/jit_compiler_x86_static.S.o
[ 45%] Building CXX object CMakeFiles/xmr-stak-randomx.dir/xmrstak/backend/cpu/crypto/randomx/jit_compiler_x86.cpp.o
[ 47%] Building CXX object CMakeFiles/xmr-stak-randomx.dir/xmrstak/backend/cpu/crypto/common/VirtualMemory_unix.cpp.o
/tmp/xmr-stak/xmrstak/backend/cpu/crypto/common/VirtualMemory_unix.cpp: In static member function 'static void* xmrstak::VirtualMemory::allocateLargePagesMemory(size_t, size_t)':
/tmp/xmr-stak/xmrstak/backend/cpu/crypto/common/VirtualMemory_unix.cpp:109:2: error: expected primary-expression before 'constexpr'
  constexpr int MAP_HUGE_2MB = (21 << MAP_HUGE_SHIFT);
  ^~~~~~~~~
/tmp/xmr-stak/xmrstak/backend/cpu/crypto/common/VirtualMemory_unix.cpp:110:2: error: expected primary-expression before 'constexpr'
  constexpr int MAP_HUGE_1GB = (30 << MAP_HUGE_SHIFT);
  ^~~~~~~~~
make[2]: *** [CMakeFiles/xmr-stak-randomx.dir/build.make:336: CMakeFiles/xmr-stak-randomx.dir/xmrstak/backend/cpu/crypto/common/VirtualMemory_unix.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:110: CMakeFiles/xmr-stak-randomx.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

```

Dockerfile:
```

FROM alpine:3.10 as build

ENV GIT_REPOSITORY=https://github.com/fireice-uk/xmr-stak.git \
    GIT_BRANCH=xmr-stak-rx-dev

COPY *.txt /xmr-stak/
RUN adduser -S -D -H -h /xmr-stak miner
RUN apk --no-cache upgrade && \
    apk --no-cache add \
      git \
      cmake \
      gcc \
      g++ \
      libuv-dev \
      openssl \
      openssl-dev \
      libc6-compat \
      build-base && \

      git clone --single-branch --depth 1 --branch $GIT_BRANCH $GIT_REPOSITORY /tmp/xmr-stak && \
      cd /tmp/xmr-stak && \
      mkdir build && \
      cd build && \
      cmake -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_INSTALL_PREFIX=/xmr-stak \
            -DCMAKE_LINK_STATIC=ON \
            -DXMR-STAK_COMPILE=generic \
            -DMICROHTTPD_ENABLE=OFF \
            -DCUDA_ENABLE=OFF \
            -DOpenCL_ENABLE=OFF \
            -DHWLOC_ENABLE=OFF \
            .. && \
      make install && \
    cd /xmr-stak && \
    rm /tmp/xmr-stak && \
    apk del \
      build-base \
      openssl-dev \
      g++ \
      gcc \
      cmake \
      git

USER miner
WORKDIR /xmr-stak

ENTRYPOINT ["nice", "-n", "19", "/xmr-stak/xmr-stak-rx"]
CMD ["--help"]

```

**Comment by psychocrypt** [comment]
Thx for th report. This issue is already fixed in the dev branch. Could you
please compile the dev branch until the next version is released.

**Comment by Rich7690** [comment]
Still getting same errors on dev branch. Using alpine 3.10 which appears to come with gcc and g++ 8.3.0 should that still work or does it require a different version?

Git log at time of build:
```
/tmp/xmr-stak$ git log
commit e5fb0e0dc42c38e8ea81a0b3f5c281bfd29c8d0e (grafted, HEAD -> xmr-stak-rx-dev, origin/xmr-stak-rx-dev)
Author: fireice-uk <fireice-uk@users.noreply.github.com>
Date:   Tue Dec 17 22:36:20 2019 +0000

    Merge pull request #2638 from psychocrypt/rx-fix-msrBoosterScript

    [RX] add warning for MSR changes
```

**Comment by Rich7690** [comment]
Oddly enough I can build on Debian with 8.3.0 just fine so that must not be it....
